### ISSUE TITLE
Impossible to get a 0 to 100 display with values between 0 and 1 mapped as "Percentage"

### ISSUE THREAD

**Issue by jmcollin78** [sbeyn/kibana-plugin-gauge-sg#2]
Hi there,

I love this plugin but since the last update (or may be a previous one), I cannot have the display as expected:

1. The values getted from Els are between 0 and 1 and represents percentage,
2. Those values are mapped to percentage type so they are correctly displayed in "Discovery" like 0 to 100 values (and not 0 to 1).

Now I want to display a gauge with:
1. green between 0 to 50 %,
2. yellow between 50% to 80 %,
3. red if above 80%

My setting was the following (before update):
gauge min: 0,
gauge max: 1,
gauve level1: 0, Green,
gauve level2: 50, Yellow
gauve level3: 80, Red

But the displayed value is always not percentage formatted (ie 0,05 % instead of 5 %) and the color didn't change at the threshold I gave.

Any clues for what happens ?

**Comment by sbeyn** [comment]
I update plugin for your issue and add size option...

**Comment by jmcollin78** [comment]
Fixed by commit https://github.com/sbeyn/kibana-plugin-gauge-sg/commit/eaa3a00e233fbc15d7a88d1685766b4074f9c97a
I will check this ASAP and keep you in touch.

**Comment by jmcollin78** [comment]
Hello again,
I test the patch but it's better but not totally ok:
- with Min=0, Max=1, level1=50, ... level4=95, the number displayed is OK but all gaude is red (ie >=95%).
![gauge-01](https://cloud.githubusercontent.com/assets/1712374/21311956/19c313e0-c5ea-11e6-9eac-219b2c384ca1.png)
- with Min=0, Max=1, level1=.5, ..., level4=.95, the color is green (yellow expected) and the value is 0.81% (80% expected).
![gauge-1](https://cloud.githubusercontent.com/assets/1712374/21312059/a7d6e382-c5ea-11e6-9745-3e93105cabc0.png)

So I'm stuck with configuration of the plugin once more.
My value is a number value (0.8) formatted as Percent value (to have 80% and not 0.8)

**Comment by jmcollin78** [comment]
I try to remove the Percent formatting value but it have not effect on the way the Gauge is displayed

**Comment by jmcollin78** [comment]
For information, I'm on the 4.x branch.

**Comment by jmcollin78** [comment]
Looking at code, it seems that bug is at lien 60 of gauge_sg_controller.js. The line should be :

`metrics[0] = { label: table.columns[nbr_c - 1].title, value: sum / nbr_r * 100 };`

Note: I remove  / $scope.vis.params.maxGauge which leads to 0.84 instead of 84

**Comment by jmcollin78** [comment]
I can confirm than this fix fixes the bug. I've made a local modification to test the proposed modification.
